FROM glenv:latest

RUN  apt-get install -y x11vnc openbox xfce4-terminal supervisor sudo zsh

ADD etc /etc


EXPOSE 5900

ADD run_supervisord.sh /sbin/
ENTRYPOINT ["sh", "/sbin/run_supervisord.sh"]




